# Use postgres/example user/password credentials
version: '3.9'

services:
  dev-db:
    image: postgres
    restart: always
    ports:
      - 5434:5434
      
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: eze
      POSTGRES_PASSWORD: H3adsh0t
      POSTGRES_DB: makea

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - "80"
    depends_on:
      - dev-db